
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/keycloak
    username: keycloak
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        driverClassName: org.postgresql.Driver