
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/keycloak
    username: keycloak
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        driverClassName: org.postgresql.Driver

feign:
  client:
    config:
      nomeFeignClienteDefinidoNoBean:
        read-timeout: 100
        connect-timeout: 100
  url:
    analisa-solicitacao: ${FEIGN_URL_ANALISA_SOLICITACAO:http://localhost:9999/api}
    cartao: ${FEIGN_URL_CARTAO:http://localhost:8888/api/cartoes}

management:
  endpoints:
    web:
      exposure:
        include: "*"


periodicidade:
  observa-cartao: ${PERIODICIDADE_OBSERVA_CARTAO:1000}